### ISSUE TITLE
Backend: Draft endpoints & endpoint details

### ISSUE THREAD

**Issue by grantlemons** [OreCart/OreCart-App#15]

**Comment by grantlemons** [comment]
Considering this is a draft, marking as closed.

**Comment by ezrichards** [comment]
Hang on, let's talk about this or at least have someone review it. 

For instance - why are all of the ID fields 8-bit integers (as opposed to, say, a UUID)?

**Comment by grantlemons** [comment]
It was reviewed by shane and alexander about a week ago, and there are several changes I think we need to make, I think alexander said he was going to make a few edits.

As for the ID, we just don't have enough stops/vans to justify UUID, the only thing that needs more than 8-bit is probably waypoints, which I can adjust.

**Comment by ezrichards** [comment]
Ok. I'm not especially worried about the number of stops/vans, but more the security of it. i.e., we don't necessarily want these 8-bit integers to be serial (auto incrementing). Like, we don't want people to just guess the ID and be able to go to that route. This could be fixed with a more sophisticated authorization system though. Thanks for clarifying.

**Comment by grantlemons** [comment]
@ezrichards 

I thought about security here, but I can't think of any instance where just incrementing an ID could cause any security issues. We shouldn't be exposing any data we don't want users to have access to (both from a best practices view and from in this app in particular).

If this was something like user accounts, I would agree with you, but if someone increments a number in a network request and gets info on the tungsten route instead of the iron route... we don't really care.

If you really think we need to use UUIDs, we can, but it is just more data that we are transmitting for the sake of security through obscurity.
