### ISSUE TITLE
Backend: Set up auth for admin backend

### ISSUE THREAD

**Issue by grantlemons** [OreCart/OreCart-App#18]

**Comment by ezrichards** [comment]
We only need auth for the admin panel backend, we won't have users on the main app.

**Comment by ezrichards** [comment]
Options:

JWT: https://dev.to/spaceofmiah/implementing-authorization-in-fastapi-a-step-by-step-guide-for-securing-your-web-applications-3b1l 

Oauth2: https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/

Email-style (preferred): https://www.twilio.com/en-us/sendgrid/email-api
